### ISSUE TITLE
Unable to start the game

### ISSUE THREAD

**Issue by Omnisch** [ManuDev9/BnGameEvoslashOpen#1]
Hi, ManuDev9!

I cloned the repo and tried to run it, but I can't start the game.
Specifically, after I clicked the Play button in the scene MainMenu, there was a panel "New node found! Do you want to connect it? y/n". I hit "yes" but nothing happened, the UI panel was not hidden, and the game didn't start to move.

In the console, I got info logs as below:

> Forcing player and node
> Sending ACKH
> receivedPacket = [{"player":"playerone","bodypart":"katana","sensortype":"orientation_abs","value": ...}]
> ...

It seemed that my phone was already connected, which meant the "yes" button worked.
My Unity version is the same, 2022.3.16f1. I don't know where the problem is. What should I do? Thanks!

**Comment by ManuDev9** [comment]
Hi @Omnisch !
If you received the packets you are basically 90% there, we just need to understand why the data is not picked up.

From here https://github.com/ManuDev9/BnGameEvoslashOpen/blob/main/Assets/Scripts/EvoslashCostants.cs
this line

    public readonly static int PLAYER_PREFERENCE_PLAYER_NUM_DEFAULT = 1;

That's the expected "player name" as integer

And in the code it is used here and converted as a string
https://github.com/ManuDev9/BnGameEvoslashOpen/blob/main/Assets/Scripts/Game/GameManagerScript.cs

        BnDatatypes.BnName player = new BnDatatypes.BnName();
        player.value = "" + PlayerPrefs.GetInt(
                EvoslashCostants.PLAYER_PREFERENCE_PLAYER_NUM,
                EvoslashCostants.PLAYER_PREFERENCE_PLAYER_NUM_DEFAULT);
        BnPlayer.setPlayer(player);

So the Bodynodes Player is called "1".

This means that the phone should send this kind of packets

    [{"player":"1","bodypart":"katana","sensortype":"orientation_abs","value": ...}]

with this configuration

You could do two things. Change the player name in the code. A very straightforward example:

        BnDatatypes.BnName player = new BnDatatypes.BnName();
        player.value = "playerone"

or go to the Android App, in Settings, change Player from "playerone" to "1"


There is no particular reason I set the Android app as "playerone", in the future I will set it as "1".
But the idea is to keep it very open and to let anyone chose what they prefer

Let me know how it goes!

**Comment by Omnisch** [comment]
Brilliant! I changed Player to "1" in the App, and that worked well!

Thank you for your help!

**Comment by ManuDev9** [comment]
You are welcome!
